BOARD_TAG	= pro5v328
ARDUINO_PORT	= /dev/tty.usbserial-AE01AAE3

ARDUINO_LIBS	= aJson DHT22 DMD Ethernet hex I2C MMA8453Q Ninja NinjaObjects RCSwitch Sensors SPI TimerOne Wire Wire/utility

include /usr/local/arduino/Arduino.mk
